; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = Firmware/src
default_envs=release

[env]
platform = atmelavr
board = micro
framework = arduino
extra_scripts = pre:Firmware/change_USB_Id.py
monitor_speed = 115200
build_flags = 
	-D MONITOR_SPEED=${env.monitor_speed}
lib_deps = 
	nicohood/HID-Project@^2.8.4

[env:release]
extends = env
build_flags =
	${env.build_flags} 
	-D DEBUG_LEVEL=0

[env:debug_raw_sensors]
extends = env
build_flags = 
	${env.build_flags}
	-D DEBUG_LEVEL=1

[env:debug_centerd_sensors]
extends = env
build_flags = 
	${env.build_flags}
	-D DEBUG_LEVEL=2

[env:debug_deadzone_filterd]
extends = env
build_flags = 
	${env.build_flags}
	-D DEBUG_LEVEL=3

[env:debug_axis_values]
extends = env
build_flags = 
	${env.build_flags}
	-D DEBUG_LEVEL=4	

[env:debug_side_by_side]
extends = env
build_flags = 
	${env.build_flags}
	-D DEBUG_LEVEL=5

[env:debug_button_state]
extends = env
build_flags = 
	${env.build_flags}
	-D DEBUG_LEVEL=6	